#!/bin/bash
# Scan protocol/include/*.pb-c.h → generate cli/proto_registry.c
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
INCLUDE_DIR="${SCRIPT_DIR}/include"
OUTPUT="${SCRIPT_DIR}/cli/proto_registry.c"
TMP="$(mktemp)"

# Collect all descriptor declarations from pb-c.h
find "$INCLUDE_DIR" -name "*.pb-c.h" -print0 2>/dev/null | while IFS= read -r -d '' h; do
    grep -oP 'extern const ProtobufCMessageDescriptor \K\w+(?=;)' "$h" 2>/dev/null || true
done | sort -u > "$TMP"

cat > "$OUTPUT" << 'HEAD'
/* AUTO-GENERATED by gen_proto_registry.sh — DO NOT EDIT */
#include <protobuf-c/protobuf-c.h>
HEAD

# Generate #includes for each pb-c.h (relative to protocol/)
find "$INCLUDE_DIR" -name "*.pb-c.h" -print0 2>/dev/null | while IFS= read -r -d '' h; do
    # Include path: relative to protocol/ dir
    rel="${h#$SCRIPT_DIR/}"
    echo "#include \"${rel}\"" >> "$OUTPUT"
done

echo "" >> "$OUTPUT"
echo "/* descriptor externs */" >> "$OUTPUT"
while IFS= read -r desc; do
    echo "extern const ProtobufCMessageDescriptor ${desc};" >> "$OUTPUT"
done < "$TMP"

cat >> "$OUTPUT" << 'MID'

const proto_reg_t g_proto_reg[] = {
MID

# Pair *_key with *_entry by package name
declare -A key_map entry_map
while IFS= read -r desc; do
    base="${desc%__descriptor}"
    pkg="${base%%__*}"
    if echo "$base" | grep -q '_key$'; then
        key_map["$pkg"]="$desc"
    elif echo "$base" | grep -q '_entry$'; then
        entry_map["$pkg"]="$desc"
    fi
done < "$TMP"

count=0
for pkg in "${!key_map[@]}"; do
    [ -n "${entry_map[$pkg]:-}" ] || continue
    cat >> "$OUTPUT" << ENTRY
    { .prefix = "s_${pkg}/", .key_desc = &${key_map[$pkg]}, .entry_desc = &${entry_map[$pkg]} },
ENTRY
    count=$((count + 1))
done

cat >> "$OUTPUT" << 'TAIL'
};
const int g_proto_reg_count = (int)(sizeof(g_proto_reg) / sizeof(g_proto_reg[0]));
TAIL

rm -f "$TMP"
echo "Generated ${count} proto registry entries → cli/proto_registry.c" >&2
